# Generated by Django 4.2 on 2023-04-29 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_id',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_id',
        ),
    ]
