# Generated by Django 4.2 on 2023-04-06 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_user_options_alter_teacher_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='user_id',
            new_name='user',
        ),
    ]
