# Generated by Django 4.2 on 2023-04-06 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_rename_user_id_teacher_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='groupleader_id',
            new_name='groupleader',
        ),
        migrations.RenameField(
            model_name='groupleader',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
